# Generated by Django 4.1.4 on 2023-01-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='https://tinyurl.com/2s39uufp', upload_to='profilepics'),
        ),
    ]
