# Generated by Django 4.1.4 on 2023-01-31 16:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='https://tinyurl.com/2s39uufp', max_length=200, upload_to=accounts.models.upload_to_path),
        ),
    ]
