# Generated by Django 4.1.4 on 2023-02-04 11:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=accounts.models.upload_to_path),
        ),
    ]
