# Generated by Django 4.1.4 on 2023-01-31 16:32

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(default='https://tinyurl.com/y9ppmvs4', max_length=200, upload_to=blogs.models.upload_to_path),
        ),
    ]
