# Generated by Django 4.1.4 on 2023-01-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_applauds_applaud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applaud',
            old_name='author',
            new_name='user',
        ),
    ]
