# Generated by Django 4.1.4 on 2023-02-01 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0008_alter_comment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='applauds',
            new_name='applaud_count',
        ),
        migrations.AlterField(
            model_name='applaud',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applauds', to='blogs.blog'),
        ),
        migrations.AlterField(
            model_name='applaud',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applauds', to=settings.AUTH_USER_MODEL),
        ),
    ]
