# AWS-RDS or Local machine - MySql
DB_NAME = ''
DB_USER = ''
DB_PASSWORD = ''
DB_PORT = 0
DB_HOST = ''

# AWS-S3
AWS_S3_ACCESS_KEY_ID = ''
AWS_S3_SECRET_ACCESS_KEY = ''
AWS_STORAGE_BUCKET_NAME = ''
AWS_QUERYSTRING_AUTH = False
